### PR TITLE
Support guzzle 7 + Laravel 8

### PR DESCRIPTION
**Pull request by austenc**
Wasn't sure if the changelog was done by something automatic or not. Let me know if you think this needs any changes, thank you!

### CODE REVIEW

**Comment by duncan3dc** [comment]
This is great, thanks @austenc!

**Comment by austenc** [comment]
Think this might make it into a release sometime in the future?

**Comment by duncan3dc** [comment]
That would help wouldn't it! I've tagged [1.3.1](https://github.com/duncan3dc/speaker/releases/tag/1.3.1) now

**Comment by austenc** [comment]
Thanks, Craig!

**Pull request merged**
